import { readFile } from "node:fs/promises";
import path from "node:path";
import { createAppAuth } from "@octokit/auth-app";
import { db } from "@bugpilot/database";
import { assertEditable } from "@bugpilot/policy";
import { McpTools } from "@bugpilot/agent";

async function token() {
  if (process.env.GITHUB_TOKEN) return process.env.GITHUB_TOKEN;
  const appId = process.env.GITHUB_APP_ID,
    installationId = process.env.GITHUB_INSTALLATION_ID,
    privateKey = process.env.GITHUB_PRIVATE_KEY?.replaceAll("\\n", "\n");
  if (!appId || !installationId || !privateKey) throw new Error("GitHub App credentials are missing");
  const auth = createAppAuth({ appId, installationId, privateKey });
  return (await auth({ type: "installation" })).token;
}
async function gh<T>(route: string, accessToken: string, init?: RequestInit) {
  const response = await fetch(`https://api.github.com${route}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${accessToken}`,
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": "BugPilot/0.1",
      "content-type": "application/json",
      ...(init?.headers ?? {}),
    },
  });
  if (!response.ok) throw new Error(`GitHub ${response.status}: ${(await response.text()).slice(0, 1200)}`);
  return (await response.json()) as T;
}

export async function publishTask(taskId: string) {
  const task = await db.task.findUniqueOrThrow({
    where: { id: taskId },
    include: { approvals: { orderBy: { createdAt: "desc" }, take: 1 } },
  });
  if (task.state !== "PUBLISHING" || !task.approvedAt || task.approvals[0]?.hash !== task.approvalHash)
    throw new Error("A matching human approval is required");
  if (!task.workspacePath || !task.baseCommit) throw new Error("Workspace is unavailable");
  const accessToken = await token(),
    owner = task.repositoryOwner,
    repo = task.repositoryName,
    branch = `bugpilot/issue-${task.issueNumber}-${task.id.slice(-6)}`;
  await gh(`/repos/${owner}/${repo}/git/refs`, accessToken, {
    method: "POST",
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: task.baseCommit }),
  });
  const mcp = new McpTools(task.id, task.workspacePath);
  await mcp.connect(["git"]);
  let changed = "";
  try {
    const raw = await mcp.callTrusted("git", "get_changed_files");
    changed = (JSON.parse(raw) as { stdout: string }).stdout;
  } finally {
    await mcp.close();
  }
  for (const line of changed.trim().split("\n").filter(Boolean)) {
    const [status, ...parts] = line.split("\t"),
      file = assertEditable(parts.at(-1) ?? "");
    const existing = await gh<{ sha: string }>(
      `/repos/${owner}/${repo}/contents/${file}?ref=${encodeURIComponent(task.baseBranch)}`,
      accessToken,
    ).catch(() => null);
    const route = `/repos/${owner}/${repo}/contents/${file}`;
    if (status.startsWith("D")) {
      if (existing)
        await gh(route, accessToken, {
          method: "DELETE",
          body: JSON.stringify({ message: `fix: issue #${task.issueNumber}`, sha: existing.sha, branch }),
        });
      continue;
    }
    const content = await readFile(path.join(task.workspacePath, file));
    await gh(route, accessToken, {
      method: "PUT",
      body: JSON.stringify({
        message: `fix: issue #${task.issueNumber}`,
        content: content.toString("base64"),
        branch,
        ...(existing ? { sha: existing.sha } : {}),
      }),
    });
  }
  const pr = await gh<{ html_url: string }>(`/repos/${owner}/${repo}/pulls`, accessToken, {
    method: "POST",
    body: JSON.stringify({
      title: `fix: ${task.issueTitle ?? `issue #${task.issueNumber}`}`,
      body: `Fixes #${task.issueNumber}\n\n${task.summary ?? "Patch generated by BugPilot."}\n\nReviewed and approved through BugPilot.`,
      head: branch,
      base: task.baseBranch,
      draft: true,
    }),
  });
  await db.$transaction([
    db.task.update({ where: { id: task.id }, data: { state: "COMPLETED", pullRequestUrl: pr.html_url } }),
    db.taskEvent.create({
      data: { taskId: task.id, type: "PR_CREATED", title: "Draft pull request created", detail: pr.html_url },
    }),
  ]);
}
