"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, ArrowLeft, Check, CheckCircle2, Circle, Clock3, Code2, Container, ExternalLink, GitBranch, Github, Play, RefreshCw, RotateCcw, ShieldCheck, Sparkles, Terminal, X, XCircle } from "lucide-react";

const API=process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:4000";
type Event={id:string;type:string;title:string;detail?:string;tool?:string;agentRole?:string;status?:string;durationMs?:number;iteration?:number;createdAt:string};
type TestRun={id:string;command:string;exitCode:number;stdout:string;stderr:string;durationMs:number};
type AgentRun={id:string;role:string;objective?:string;parentRunId?:string;status:string;iteration:number;toolCalls:number;modelCalls:number;durationMs?:number;output?:Record<string,unknown>};
type Task={id:string;repositoryUrl:string;repositoryOwner:string;repositoryName:string;issueNumber:number;issueTitle?:string;issueBody?:string;baseBranch:string;state:string;currentAgent?:string;summary?:string;diff?:string;approvalHash?:string;approvedAt?:string;pullRequestUrl?:string;error?:string;createdAt:string;updatedAt:string;events?:Event[];testRuns?:TestRun[];agentRuns?:AgentRun[];managerPlan?:any;researchReport?:any;patchProposal?:any;testReport?:any;reviewReport?:any};
type Health={ok:boolean;database:boolean;docker:boolean;gemini:boolean;github:boolean};
const terminal=new Set(["COMPLETED","FAILED","REJECTED","AWAITING_APPROVAL"]);
const stages=["PREPARING","RESEARCHING","CODING","TESTING","REVIEWING","AWAITING_HUMAN_APPROVAL","PUBLISHING","COMPLETED"];
function displayState(state:string){return state.replaceAll("_"," ").toLowerCase().replace(/^./,c=>c.toUpperCase());}

export default function Home(){
  const [tasks,setTasks]=useState<Task[]>([]),[selected,setSelected]=useState<string>(),[health,setHealth]=useState<Health>(),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{try{const [taskResponse,healthResponse]=await Promise.all([fetch(`${API}/tasks`,{cache:"no-store"}),fetch(`${API}/health`,{cache:"no-store"})]);if(taskResponse.ok)setTasks(await taskResponse.json());if(healthResponse.ok)setHealth(await healthResponse.json());}finally{setLoading(false)}},[]);
  useEffect(()=>{load();const timer=setInterval(load,4000);return()=>clearInterval(timer)},[load]);
  return <main><Header health={health}/>{selected?<TaskDetail id={selected} onBack={()=>{setSelected(undefined);load()}}/>:<Dashboard tasks={tasks} loading={loading} health={health} onOpen={setSelected} onCreated={id=>{setSelected(id);load()}}/>}</main>
}

function Header({health}:{health?:Health}){return <header><div className="brand"><div className="brandMark"><GitBranch size={20}/></div><span>BugPilot</span><span className="beta">BETA</span></div><div className="headerRight"><span className={`statusDot ${health?.ok?"ok":""}`}/><span>{health?.ok?"System online":"Setup required"}</span><a className="githubLink" href="https://github.com" target="_blank"><Github size={18}/></a></div></header>}

function Dashboard({tasks,loading,health,onOpen,onCreated}:{tasks:Task[];loading:boolean;health?:Health;onOpen:(id:string)=>void;onCreated:(id:string)=>void}){
  const stats={runs:tasks.length,completed:tasks.filter(t=>t.state==="COMPLETED").length,review:tasks.filter(t=>t.state==="AWAITING_HUMAN_APPROVAL").length};
  return <div className="shell"><section className="hero"><div><div className="eyebrow"><Sparkles size={14}/> AUTONOMOUS ISSUE RESOLUTION</div><h1>From issue to <em>verified patch.</em></h1><p>BugPilot investigates GitHub issues, edits code through MCP, runs checks in an isolated container, and waits for your approval before opening a draft PR.</p></div><NewTask onCreated={onCreated}/></section>
    <Readiness health={health}/>
    <section className="stats"><Stat icon={<Activity/>} label="Total runs" value={stats.runs}/><Stat icon={<CheckCircle2/>} label="Completed" value={stats.completed}/><Stat icon={<ShieldCheck/>} label="Awaiting review" value={stats.review}/></section>
    <section className="runs"><div className="sectionTitle"><div><h2>Agent runs</h2><p>Every decision and tool call is recorded.</p></div><button className="iconButton" onClick={()=>location.reload()}><RefreshCw size={16}/></button></div>
    {loading?<div className="empty">Loading runs…</div>:tasks.length===0?<div className="empty"><div className="emptyIcon"><Code2/></div><h3>No runs yet</h3><p>Start with the included demo fixture or enter a public GitHub issue.</p></div>:<div className="runList">{tasks.map(task=><button className="runRow" key={task.id} onClick={()=>onOpen(task.id)}><div className={`stateIcon ${task.state.toLowerCase()}`}>{task.state==="COMPLETED"?<Check size={17}/>:task.state==="FAILED"?<X size={17}/>:<Circle size={15}/>}</div><div className="runMain"><strong>{task.issueTitle??`Issue #${task.issueNumber}`}</strong><span><Github size={13}/>{task.repositoryOwner}/{task.repositoryName} · #{task.issueNumber}</span></div><span className={`badge ${task.state.toLowerCase()}`}>{displayState(task.state)}</span><span className="date">{new Date(task.createdAt).toLocaleDateString()}</span></button>)}</div>}</section>
  </div>
}

function NewTask({onCreated}:{onCreated:(id:string)=>void}){const [repositoryUrl,setRepositoryUrl]=useState(""),[issueNumber,setIssueNumber]=useState(""),[sending,setSending]=useState(false),[error,setError]=useState("");async function submit(demo=false){setSending(true);setError("");try{const body=demo?{repositoryUrl:"https://github.com/bugpilot/demo",issueNumber:1,issueTitle:"add() subtracts instead of adding",issueBody:"The add function returns the wrong result. Make the smallest correction and ensure tests pass.",baseBranch:"main",demoMode:true}:{repositoryUrl,issueNumber:Number(issueNumber),baseBranch:"main",demoMode:false};const response=await fetch(`${API}/tasks`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error??"Could not create task");onCreated(data.id)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setSending(false)}}return <div className="launchCard"><div className="launchTop"><div><span>Launch an agent</span><small>Public GitHub repositories</small></div><Terminal size={20}/></div><label>Repository URL<input value={repositoryUrl} onChange={e=>setRepositoryUrl(e.target.value)} placeholder="https://github.com/owner/repo"/></label><div className="formRow"><label>Issue number<input value={issueNumber} onChange={e=>setIssueNumber(e.target.value)} inputMode="numeric" placeholder="42"/></label><label>Base branch<input value="main" readOnly/></label></div>{error&&<p className="formError">{error}</p>}<button className="primary" disabled={sending} onClick={()=>submit(false)}><Play size={15} fill="currentColor"/>{sending?"Starting…":"Run BugPilot"}</button><button className="demoButton" disabled={sending} onClick={()=>submit(true)}>Try the built-in demo fixture</button></div>}

function Readiness({health}:{health?:Health}){if(!health||Object.values(health).every(Boolean))return null;return <section className="readiness"><div><Container/><div><strong>Finish local setup</strong><p>BugPilot keeps unsafe repository code inside Docker.</p></div></div><div className="checks"><MiniCheck ok={health.database} text="PostgreSQL"/><MiniCheck ok={health.docker} text="Docker"/><MiniCheck ok={health.gemini} text="Gemini"/><MiniCheck ok={health.github} text="GitHub publish" optional/></div></section>}
function MiniCheck({ok,text,optional}:{ok?:boolean;text:string;optional?:boolean}){return <span className={ok?"ready":"missing"}>{ok?<Check size={13}/>:<X size={13}/>} {text}{optional&&!ok?" (later)":""}</span>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="stat"><div className="statIcon">{icon}</div><div><strong>{value}</strong><span>{label}</span></div></div>}

function TaskDetail({id,onBack}:{id:string;onBack:()=>void}){const [task,setTask]=useState<Task>(),[tab,setTab]=useState<"review"|"agents"|"diff"|"tests"|"timeline">("agents"),[busy,setBusy]=useState(false),[actionError,setActionError]=useState("");const load=useCallback(async()=>{const r=await fetch(`${API}/tasks/${id}`,{cache:"no-store"});if(r.ok)setTask(await r.json())},[id]);useEffect(()=>{load();const timer=setInterval(load,1500);return()=>clearInterval(timer)},[load]);async function decide(decision:string){setBusy(true);setActionError("");try{const note=decision==="reject"?prompt("What should the agents change?")??"":"";const response=await fetch(`${API}/tasks/${id}/decision`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({decision,note})}),data=await response.json();if(!response.ok)throw new Error(data.error??"The decision could not be saved");await load()}catch(error){setActionError(error instanceof Error?error.message:String(error))}finally{setBusy(false)}}async function resume(){setBusy(true);setActionError("");try{const response=await fetch(`${API}/tasks/${id}/resume`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"}),data=await response.json();if(!response.ok)throw new Error(data.error??"The run could not be resumed");await load()}catch(error){setActionError(error instanceof Error?error.message:String(error))}finally{setBusy(false)}}if(!task)return <div className="shell loading">Loading task…</div>;const current=Math.max(0,stages.indexOf(task.state)),canResume=task.state==="FAILED"||task.state==="NEEDS_ATTENTION",publishResume=Boolean(task.approvedAt&&task.approvalHash);return <div className="shell detail"><button className="back" onClick={onBack}><ArrowLeft size={16}/> All runs</button><section className="taskHead"><div><div className="repo"><Github size={15}/>{task.repositoryOwner}/{task.repositoryName} <span>#{task.issueNumber}</span></div><h1>{task.issueTitle??"Loading issue…"}</h1><p>{task.issueBody}</p></div><div className="headStatus">{task.currentAgent&&<span className="currentAgent"><Activity size={13}/> Current agent: {displayState(task.currentAgent)}</span>}<span className={`badge large ${task.state.toLowerCase()}`}>{displayState(task.state)}</span></div></section>
    <div className="progress">{stages.map((stage,index)=><div key={stage} className={index<current?"done":index===current?"active":""}><span>{index<current?<Check size={12}/>:index+1}</span><small>{stage==="AWAITING_APPROVAL"?"Approval":displayState(stage)}</small></div>)}</div>
    {(task.error||actionError)&&<div className="errorPanel"><XCircle/><div><strong>Run stopped</strong><pre>{actionError||task.error}</pre></div>{canResume&&<button className="resumeButton" disabled={busy} onClick={resume}><RotateCcw size={15}/>{busy?"Resuming…":publishResume?"Retry draft PR publish":"Resume from checkpoint"}</button>}</div>}
    {task.state==="AWAITING_HUMAN_APPROVAL"&&<div className="approval"><div><ShieldCheck/><div><strong>Reviewer approved · human authorization required</strong><p>Approval applies only to fingerprint <code>{task.approvalHash?.slice(0,16)}</code>. Any code, branch, base commit, or test change invalidates it.</p></div></div><div><button className="reject" disabled={busy} onClick={()=>decide("reject")}><X size={15}/> Reject</button><button className="approve" disabled={busy} onClick={()=>decide("approve")}><Check size={15}/> Approve & create draft PR</button></div></div>}
    {task.pullRequestUrl&&<a className="prBanner" href={task.pullRequestUrl} target="_blank"><CheckCircle2/><div><strong>Draft pull request created</strong><span>{task.pullRequestUrl}</span></div><ExternalLink/></a>}
    <section className="workspace"><div className="tabs"><button className={tab==="agents"?"active":""} onClick={()=>setTab("agents")}>Agent team <span>{task.agentRuns?.length??0}</span></button><button className={tab==="review"?"active":""} onClick={()=>setTab("review")}>Review brief</button><button className={tab==="diff"?"active":""} onClick={()=>setTab("diff")}>Code diff</button><button className={tab==="tests"?"active":""} onClick={()=>setTab("tests")}>Checks <span>{task.testRuns?.length??0}</span></button><button className={tab==="timeline"?"active":""} onClick={()=>setTab("timeline")}>Full timeline <span>{task.events?.length??0}</span></button></div>{tab==="agents"?<AgentBoard runs={task.agentRuns??[]}/>:tab==="review"?<ReviewBrief task={task}/>:tab==="diff"?<DiffView diff={task.diff}/>:tab==="tests"?<Tests runs={task.testRuns??[]} report={task.testReport}/>:<Timeline events={task.events??[]}/>}</section>
  </div>}

function AgentBoard({runs}:{runs:AgentRun[]}){const roles=["MANAGER","RESEARCHER","CODER","TESTER","REVIEWER"],research=runs.filter(r=>r.role==="RESEARCHER");return <div className="agentBoard"><div className="agentFlow">{roles.map((role,i)=><span key={role}>{displayState(role)}{i<roles.length-1&&<b>→</b>}</span>)}</div>{research.length>1&&<div className="parallelRuns"><strong>Parallel research branches</strong><div>{research.map(run=><article key={run.id}><span>Researcher</span><p>{run.objective}</p><small>{run.status} · {run.toolCalls} tools · {run.durationMs?`${(run.durationMs/1000).toFixed(1)}s`:"running"}</small></article>)}</div></div>}<div className="agentGrid">{roles.map(role=>{const roleRuns=runs.filter(r=>r.role===role),last=roleRuns.at(-1);return <div className={`agentCard ${last?.status.toLowerCase()??"waiting"}`} key={role}><div><span className="agentAvatar">{role[0]}</span><div><strong>{displayState(role)}</strong><small>{last?.status??"WAITING"}</small></div></div><p>{last?.objective??(role==="MANAGER"?"Plans and delegates":role==="RESEARCHER"?"Read-only diagnosis":role==="CODER"?"Scoped patching":role==="TESTER"?"Docker verification":"Independent assessment")}</p><footer><span>{roleRuns.length} run{roleRuns.length===1?"":"s"}</span><span>{roleRuns.reduce((n,r)=>n+r.toolCalls,0)} tools</span><span>{last?.durationMs?`${(last.durationMs/1000).toFixed(1)}s`:"—"}</span></footer></div>})}</div></div>}
function ReviewBrief({task}:{task:Task}){const research=task.researchReport,patch=task.patchProposal,review=task.reviewReport;return <div className="brief"><Brief title="1. Original issue"><p>{task.issueBody??"Issue details are loading."}</p></Brief><Brief title="2. Research diagnosis"><p>{research?.diagnosis??"Pending"}</p>{research?.evidence?.map((e:any,i:number)=><code key={i}>{e.path}{e.line?`:${e.line}`:""} · {e.observation}</code>)}</Brief><Brief title="3. Proposed implementation"><p>{research?.proposedApproach??patch?.rationale??"Pending"}</p></Brief><Brief title="4. Changed files"><p>{patch?.filesChanged?.join(", ")??"Pending"}</p></Brief><Brief title="5. Test evidence"><p>{task.testReport?.summary??"Pending"}</p></Brief><Brief title="6. Independent reviewer"><p>{review?.reasoning??"Pending"}</p>{review&&<span className={`reviewDecision ${review.decision}`}>{review.decision} · {review.scopeAssessment} scope · {review.regressionRisk} risk</span>}</Brief></div>}
function Brief({title,children}:{title:string;children:React.ReactNode}){return <section><h3>{title}</h3>{children}</section>}

function DiffView({diff}:{diff?:string}){if(!diff)return <div className="empty compact"><Clock3/><p>The patch will appear after the agent finishes editing and testing.</p></div>;return <div className="diff">{diff.split("\n").map((line,i)=><div key={i} className={line.startsWith("+")&&!line.startsWith("+++")?"add":line.startsWith("-")&&!line.startsWith("---")?"remove":line.startsWith("@@")?"hunk":line.startsWith("diff ")?"file":""}><span>{i+1}</span><code>{line||" "}</code></div>)}</div>}
function Tests({runs,report}:{runs:TestRun[];report?:{passed?:boolean}}){if(!runs.length)return <div className="empty compact">No checks recorded yet.</div>;return <div className="testList">{runs.map(run=>{const passed=run.exitCode===0,advisory=!passed&&report?.passed===true;return <div className="test" key={run.id}><div><span className={passed?"pass":advisory?"advisory":"fail"}>{passed?<Check/>:advisory?<AlertTriangle/>:<X/>}</span><strong>{run.command}</strong>{advisory&&<b className="advisoryLabel">Advisory</b>}<small>{(run.durationMs/1000).toFixed(1)}s · Docker sandbox</small></div><pre>{run.stdout||run.stderr}</pre></div>})}</div>}
function Timeline({events}:{events:Event[]}){return <div className="timeline">{events.map((event,i)=><div className="event" key={event.id}><div className="rail"><span className={event.type.includes("FAILED")?"failed":event.type==="TOOL_COMPLETED"?"tool":""}>{event.tool?<Terminal size={13}/>:<Circle size={10} fill="currentColor"/>}</span>{i<events.length-1&&<i/>}</div><div><strong>{event.title}</strong>{event.agentRole&&<b className="roleTag">{event.agentRole}</b>}<small>{event.durationMs?`${event.durationMs}ms · `:""}{new Date(event.createdAt).toLocaleTimeString()}</small>{event.detail&&<pre>{event.detail}</pre>}</div></div>)}</div>}
