import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
const text=(value:unknown)=>({content:[{type:"text" as const,text:JSON.stringify(value)}]});
const server=new McpServer({name:"bugpilot-github",version:"0.1.0"});
server.tool("read_issue","Read a public GitHub issue",{owner:z.string(),repo:z.string(),issueNumber:z.number().int().positive()},async({owner,repo,issueNumber})=>{
  const response=await fetch(`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/issues/${issueNumber}`,{headers:{Accept:"application/vnd.github+json","User-Agent":"BugPilot/0.1"}});
  if(!response.ok) throw new Error(`GitHub returned ${response.status}`);
  const issue=await response.json() as {title:string;body:string|null;html_url:string;state:string;pull_request?:unknown};
  if(issue.pull_request) throw new Error("The selected number is a pull request");
  return text({title:issue.title,body:issue.body??"",url:issue.html_url,state:issue.state});
});
server.tool("prepare_draft_pr","Prepare the reviewed PR metadata. Publishing is performed only by the trusted control plane after approval.",{owner:z.string(),repo:z.string(),issueNumber:z.number(),summary:z.string(),branch:z.string()},async(input)=>text({title:`fix: ${input.summary.slice(0,72)}`,body:`Fixes #${input.issueNumber}\n\n${input.summary}\n\nGenerated by BugPilot and approved by a human.`,head:input.branch,base:"main",draft:true}));
await server.connect(new StdioServerTransport());
